[tools]
babashka = "latest"
bun = "latest"
clojure = "latest"
go = "latest"
java = "temurin-25"
node = "24"
python = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"
zig = "latest"
zls = "latest"
